# Generated by Django 3.1.6 on 2021-02-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0004_auto_20210207_2021'),
    ]

    operations = [
    ]
