# Generated by Django 3.1.6 on 2021-02-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0005_auto_20210209_1150'),
    ]

    operations = [
    ]
