# Generated by Django 3.1.6 on 2021-02-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0006_auto_20210211_1235'),
    ]

    operations = [
    ]
